apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: echo-kustomize-root
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/maciejkozubal/argocd.git
    targetRevision: main
    path: 3-kustomize/apps
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true