apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  sourceRepos:
    - https://github.com/maciejkozubal/argocd.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: echo-*
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
  roles:
    - name: dev
      policies:
        - p, proj:apps:dev, applications, sync, apps/*, allow