apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: echo-prod
  namespace: argocd
spec: 
  project: default
  source:
    repoURL: https://github.com/maciejkozubal/argocd
    targetRevision: main
    path: 1-multi-env/workloads/echo
    helm: {valueFiles: [values-prod.yml]}
  destination:
    server: https://kubernetes.default.svc
    namespace: echo-prod
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]